import { Inter } from "next/font/google";
import "./globals.css";
import Model from "@/components/ui/Model";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Master' Union",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Model />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
